/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/uEsS2cOl7j6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function button() {
  return <Button>Button</Button>;
}
